/**
 * @param { app, context }
 * app { navigate, setGlobalState, setSearchParams }
 * context { globalState, searchParams, params, location }
 * globalState { data: string | object | array, loading: boolean, error: string  }
 */

/**
 * setGlobalState { [globalStateName: string] : (previousState) => newState }
 *
 * example:
 * Insert new `auth` state -> setGlobalState.auth((prev) => ({...prev, name: "Steve"}))
 */

// function below generated by system, you can't remove or rename it!
export const onClick = ({ app, context }) => {
  app.navigate("/news/9");
};
